version: '3.8'
services:
  api:
    image: tyroroto/hype-api:main
    ports:
      - "${HYPE_API_PORT}:3000"
    depends_on:
      - migrate
    command: yarn start:prod
    environment:
      DATABASE_HOST: ${HYPE_DB_HOST}
      DATABASE_PORT: ${HYPE_DB_PORT}
      DATABASE_USERNAME: ${HYPE_DB_USERNAME}
      DATABASE_PASSWORD: ${HYPE_DB_PASSWORD}
      DATABASE_DB: ${HYPE_DB}
  migrate:
    image: tyroroto/hype-api:main
    command: sh -c "node init-config.js && cat config/config.json && yarn run migrate:prod && yarn run migrate:prod:seed"
    environment:
      DATABASE_HOST: ${HYPE_DB_HOST}
      DATABASE_PORT: ${HYPE_DB_PORT}
      DATABASE_USERNAME: ${HYPE_DB_USERNAME}
      DATABASE_PASSWORD: ${HYPE_DB_PASSWORD}
      DATABASE_DB: ${HYPE_DB}
